### ISSUE TITLE
doesn't let me queue or certain tabs

### ISSUE THREAD

**Issue by Squimbert** [derfloh205/PvPAssistant#15]
when the addon is enabled my grouping pane looks like this:

![image](https://github.com/derfloh205/PvPAssistant/assets/99698377/0ad5c4f6-664c-4b3a-b49d-28ff343dcbb4)

cannot click "Rated"" or "Premade Groups".

as soon as i disable the addon i am able to click them again.

**Comment by Thekinghim** [comment]
We are working on a fix to that as we speak, Has been a lot of irl stuff currently! If you have a fix to the problem you are more the welcome to fork/PR to the repo :)

**Comment by derfloh205** [comment]
Will be fixed with beta0.1.10+
