### ISSUE TITLE
Match History: Matches not showing in Match History

### ISSUE THREAD

**Issue by derfloh205** [derfloh205/PvPAssistant#37]
![image](https://github.com/derfloh205/PvPAssistant/assets/9341090/5e9eff8d-3ca8-403f-a786-fb9d137a0369)

**Comment by Thekinghim** [comment]
Still not working we also have data
![f79ca5af701e5edb290351c4ca656301 (1)](https://github.com/derfloh205/PvPAssistant/assets/151988881/0753c08e-f0c0-4618-8e7c-37efc90f7733)

**Comment by Thekinghim** [comment]
Weird it works on my other chars but now my pala

**Comment by Thekinghim** [comment]
![dc1a908092f01a5f87ccca1a1fcb83ed](https://github.com/derfloh205/PvPAssistant/assets/151988881/8b496522-af5e-42b6-bba9-237827b8b166)

**Comment by derfloh205** [comment]
![image](https://github.com/derfloh205/PvPAssistant/assets/9341090/159272e2-5611-40ba-bf8b-0a981c1dd11b)
On Data Collect
