### ISSUE TITLE
This error came up when i logged on a new char

### ISSUE THREAD

**Issue by Thekinghim** [derfloh205/PvPAssistant#58]
`Message: Usage: local classColor = C_ClassColor.GetClassColor(className)
Time: Sat Mar 23 18:33:09 2024
Count: 2
Stack: Usage: local classColor = C_ClassColor.GetClassColor(className)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetClassColor'
[string "@Interface/AddOns/PvpAssistant/Libs/GGUI/GGUI.lua"]:3963: in function `SetClass'
[string "@Interface/AddOns/PvpAssistant/Modules/ArenaGuide/Frames.lua"]:254: in function `UpdateDisplay'
[string "@Interface/AddOns/PvpAssistant/Modules/ArenaGuide/ArenaGuide.lua"]:22: in function `UpdateAndShow'
[string "@Interface/AddOns/PvpAssistant/Modules/ArenaGuide/ArenaGuide.lua"]:59: in function `?'
[string "@Interface/AddOns/PvpAssistant/Libs/GUTIL/GUTIL.lua"]:232: in function <Interface/AddOns/PvpAssistant/Libs/GUTIL/GUTIL.lua:232>

Locals: (*temporary) = <function> defined =[C]:-1`

**Comment by derfloh205** [comment]
Logged in or when going into arena?

**Comment by Thekinghim** [comment]
When I logged into the character that popped up
