### ISSUE TITLE
I have 2 accounts on wow and i have noticed that on my WOW1 the match history does not work

### ISSUE THREAD

**Issue by Thekinghim** [derfloh205/PvPAssistant#61]
So as i have stated before on my WOW2 the history works as it should but for some reason my secound account nothing is working. There is data for the relevent character im on
![78a6ad3d756d92ef54b5649b53e6ef31](https://github.com/derfloh205/PvPAssistant/assets/151988881/f6014bf2-1039-4f92-a04b-8477b3a43f26)

**Comment by Thekinghim** [comment]
Never mind something is very wrong, It only works on 2 of my character the other ones shows nothing

**Comment by derfloh205** [comment]
Can you send me your saved variable files per discord DM ?

**Comment by derfloh205** [comment]
@Thekinghim Please check if this issue is a possible duplicate with #37

**Comment by derfloh205** [comment]
Hm it very much seems so, Lets continue this in the other issue: #37
