### ISSUE TITLE
Make the Appearance of the Donation Button consistent with the webpage it links to and make the Background transparent

### ISSUE THREAD

**Issue by derfloh205** [derfloh205/PvPAssistant#66]
Currently the button has the Patreon Icon but the URL it links to is a kofi donation page

Change the icon of the button to a kofi icon

Also make the background of the button transparent similar to the discord button

**Comment by Thekinghim** [comment]
Yes I will take a look at this when I'm home

**Comment by Thekinghim** [comment]
But how do I make the background transparent?

**Comment by iam3yal** [comment]
Probably need to add alpha channel.

**Comment by Thekinghim** [comment]
Done
