### ISSUE TITLE
Bug: Frames.lua:1136: attempt to index field 'player'

### ISSUE THREAD

**Issue by iam3yal** [derfloh205/PvPAssistant#67]
I've downloaded the addon straight from curse (version 0.1.12) and I'm getting the following error and it seems like it happens only on one of my characters. I'm looking into it.
```lua
Message: ...ace/AddOns/PvpAssistant/Modules/MainFrame/Frames.lua:1136: attempt to index field 'player' (a nil value)
Time: Tue Mar 26 22:42:24 2024
Count: 1
Stack: ...ace/AddOns/PvpAssistant/Modules/MainFrame/Frames.lua:1136: attempt to index field 'player' (a nil value)
[string "@Interface/AddOns/PvpAssistant/Modules/MainFrame/Frames.lua"]:1136: in function `filterFunc'
[string "@Interface/AddOns/PvpAssistant/Libs/GUTIL/GUTIL.lua"]:223: in function `Filter'
[string "@Interface/AddOns/PvpAssistant/Modules/MainFrame/Frames.lua"]:1134: in function `UpdateMatchHistory'
[string "@Interface/AddOns/PvpAssistant/Main/PvPAssistant.lua"]:134: in function `?'
[string "@Interface/AddOns/PvpAssistant/Libs/GUTIL/GUTIL.lua"]:232: in function <Interface/AddOns/PvpAssistant/Libs/GUTIL/GUTIL.lua:232>

Locals: matchHistory = <table> {
 mapInfo = <table> {
 }
 win = true
 duration = 0
 pvpMode = false
 season = 36
 isBattleground = false
 isArena = false
 isSoloShuffle = false
 isRated = false
 playerTeam = <table> {
 }
 timestamp = 1711488180000
 pvpMatchState = 0
 enemyTeam = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'player' (a nil value)"
selectedCharacterUID = "Seed-BronzeDragonflight"
pvpModeFilter = nil
```

**Comment by derfloh205** [comment]
might have something to do with my recent added migration for match history or there is still outdated matchhistory in your saved variables
there is a slash command to wipe it
hmm i think /pa history clear

**Comment by iam3yal** [comment]
@derfloh205 Well, I forgot to mention but I didn't have the addon before so I didn't have any history, it was a fresh install with fresh SV but I'll try to use the command.

**Comment by derfloh205** [comment]
so fresh install and then straight into a pvp game?

**Comment by iam3yal** [comment]
@derfloh205 No, fresh install and the first time I logged into the game that's what I got and it persisted between game sessions and reloads until I did `/pa history clear`. 

Weirdly enough it happened only on the first character that I was firstly logged into.

**Comment by derfloh205** [comment]
@iam3yal 

I tried to reproduce this:

1.) Go into the WTF Folder and delete my PvPAssistant.lua file while logged out
2.) Log in to test the initial load of a fresh install
3.) Everything works as expected, no errors

**Comment by derfloh205** [comment]
Are you very sure this was a fresh install?
The error seems to have occured in the filter function for the match histories which is executed before any histories are added to the list

this function is actually not even called when you dont have any histories saved
which should be the case when you have a fresh install and thus no saved matches for your character
