### ISSUE TITLE
ArenaGuide: Spec Icons for Enemies are not shown correctly

### ISSUE THREAD

**Issue by derfloh205** [derfloh205/PvPAssistant#75]
![WoWScrnShot_032824_065809](https://github.com/derfloh205/PvPAssistant/assets/9341090/55e60ce9-a24f-4abd-9a2b-a98ba24a20bc)

The strategy text shows the enemy arms warrior correctly but the icon was not displayed

enemies were demonology warlock and arms warrior

I was alone in my team (Could this be the issue?

**Comment by derfloh205** [comment]
Here it worked
![WoWScrnShot_032824_071205](https://github.com/derfloh205/PvPAssistant/assets/9341090/36e2b557-e055-4819-bb20-ea26c7999668)

Note: In the first screenshot gladius did also not load the enemy frames yet!

This could be due to some event not firing or some infos not being available yet?

Probably has something to do that I loaded alone into the first match

**Comment by Thekinghim** [comment]
Hey i wanted to tell you why it did not load. All of the team memebers needs to be loaded before any addon can be

**Comment by Thekinghim** [comment]
The issue is that our enemy and your team has not accpeted the invite thats why the gladius and arena quick guide does not work

**Comment by Thekinghim** [comment]
@derfloh205 I dont think that anything is wrong with the arena quick guide. I have had the same stuff happen to me when a player joins late or has a very long loading screen. 

Side not: I have never seen the arena strategie text that you saw :O
